name: tmtrade_sms
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_screenutil: ^5.5.4
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  intl: ^0.18.0
  uuid: ^3.0.7
  provider: ^6.0.3

  # DATABASE
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15

  # NETWORKING
  retrofit: ^3.3.0
  dio: ^4.0.6
  awesome_dio_interceptor: ^0.0.2+4
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^2.3.0

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.2
  equatable: ^2.0.3
  get_it: ^7.2.0

  # File
  # open_file: ^3.3.2
  # syncfusion_flutter_pdfviewer: ^20.3.49
  # advance_pdf_viewer: ^2.0.1
  # file_picker: ^5.2.2
  # path_provider: ^2.0.11
  # open_filex: ^4.3.1
  # permission_handler: ^10.2.0
  # percent_indicator: ^4.2.2

  # PUSH NOTIFICATIONS
  # firebase_core: ^2.6.1
  # firebase_messaging: ^14.2.4
  # flutter_local_notifications: ^13.0.0

  # IMAGE
  # image_picker: ^0.8.5+3
  # image_cropper: ^3.0.1

  # CHAT
  # web_socket_channel: ^2.2.0
  # badges: ^2.0.3
  # grouped_list: ^5.1.2

  # VIDEO
  # video_player: ^2.4.10
  # chewie: ^1.4.0
  # video_player_web_hls: ^0.1.1
  # video_player: ^0.10.10

  # OTHER
  # tutorial_coach_mark: ^1.2.4
  # webview_flutter: ^4.0.6
  # google_maps_flutter: ^2.2.1
  # visibility_detector: ^0.4.0+2
  # eraser: ^2.0.1
  # location_permissions: ^4.0.1
  # geolocator: ^9.0.2
  # flutter_hooks: ^0.18.5+1
  # floor: ^1.4.1
  # oktoast: ^3.3.1
  # auto_route: ^5.0.4
  # share_plus: ^7.0.2
  string_validator: ^1.0.0
  # carousel_slider: ^4.1.1
  # shimmer: ^2.0.0
  # flutter_staggered_grid_view: ^0.4.0
  # cached_network_image: ^3.2.1
  # url_launcher: ^6.1.5
  # photo_view: ^0.14.0
  # smooth_page_indicator: ^1.0.0+2
  # provider: ^6.0.1
  # fluttertoast: ^8.0.8
  # store_redirect: ^2.0.1
  # flutter_map: ^0.14.0
  # latlong2: ^0.8.1
  # modal_bottom_sheet: ^3.0.0-pre
  # introduction_screen: ^3.0.2
  # pull_to_refresh: ^2.0.0
  # uni_links: ^0.5.1
  # restart_app: ^1.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # json_serializable: ^6.5.4
  # hive_generator: ^2.0.0
  # flutter_lints: ^2.0.0

  # auto_route_generator: ^5.0.3
  # retrofit_generator: ^4.1.2
  # floor_generator: ^1.4.1
  # build_runner: ^2.3.3



flutter:
  uses-material-design: true

  assets:
    - lang/
  #   - assets/images/
  #   - assets/vectors/

  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #       - asset: assets/fonts/OpenSans-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/OpenSans-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/OpenSans-Bold.ttf
  #         weight: 700

